"""empty message

Revision ID: 05cc496ce3ce
Revises: 6e08864ed652
Create Date: 2026-01-15 18:29:42.296491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cc496ce3ce'
down_revision = '6e08864ed652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.Text(), server_default=sa.text("''::text"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_column('tool')

    # ### end Alembic commands ###
