"""empty message

Revision ID: 6e08864ed652
Revises: 2fe67a77f10f
Create Date: 2026-01-15 18:26:00.648267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e08864ed652'
down_revision = '2fe67a77f10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation', sa.Text(), server_default=sa.text("''::text"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_column('observation')

    # ### end Alembic commands ###
