"""empty message

Revision ID: 716fd561311f
Revises: 7630506b37fd
Create Date: 2025-11-29 16:05:38.037239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716fd561311f'
down_revision = '7630506b37fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
