"""initial_schema

Revision ID: 7d5ed54f23e7
Revises: 
Create Date: 2026-02-14 23:55:55.377499

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d5ed54f23e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('password', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('password_salt', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('last_login_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('last_login_ip', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_account_id')
                    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('account_email_idx', ['email'], unique=False)

    op.create_table('account_oauth',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('provider', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('openid', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('encrypted_token', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_account_oauth_id')
                    )
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.create_index('account_oauth_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('account_oauth_openid_provider_idx', ['openid', 'provider'], unique=False)

    op.create_table('api_key',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('api_key', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('remark', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_api_key_id')
                    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index('api_key_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_key_api_key_idx', ['api_key'], unique=False)

    op.create_table('api_tool',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('provider_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('url', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('method', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_api_tool_id')
                    )
    with op.batch_alter_table('api_tool', schema=None) as batch_op:
        batch_op.create_index('api_tool_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_tool_provider_id_name_idx', ['provider_id', 'name'], unique=False)

    op.create_table('api_tool_provider',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('openapi_schema', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_api_tool_provider_id')
                    )
    with op.batch_alter_table('api_tool_provider', schema=None) as batch_op:
        batch_op.create_index('api_tool_provider_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_tool_provider_name_idx', ['name'], unique=False)

    op.create_table('app',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('app_config_id', sa.UUID(), nullable=True),
                    sa.Column('draft_app_config_id', sa.UUID(), nullable=True),
                    sa.Column('debug_conversation_id', sa.UUID(), nullable=True),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('token', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_app_id')
                    )
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index('app_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('app_token_idx', ['token'], unique=False)

    op.create_table('app_config',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('dialog_round', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('preset_prompt', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('workflows', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('retrieval_config', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('long_term_memory', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('opening_statement', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('opening_questions', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('speech_to_text', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('text_to_speech', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('suggested_after_answer', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text('\'{"enable": true}\'::jsonb'), nullable=False),
                    sa.Column('review_config', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_app_config_id')
                    )
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index('app_config_app_id_idx', ['app_id'], unique=False)

    op.create_table('app_config_version',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('dialog_round', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('preset_prompt', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('workflows', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('datasets', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('retrieval_config', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('long_term_memory', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('opening_statement', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('opening_questions', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('speech_to_text', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('text_to_speech', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('suggested_after_answer', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text('\'{"enable": true}\'::jsonb'), nullable=False),
                    sa.Column('review_config', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('config_type', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_app_config_version_id')
                    )
    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.create_index('app_config_version_app_id_idx', ['app_id'], unique=False)

    op.create_table('app_dataset_join',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_app_dataset_join_id')
                    )
    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.create_index('app_dataset_join_app_id_dataset_id_idx', ['app_id', 'dataset_id'], unique=False)

    op.create_table('conversation',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('summary', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('invoke_from', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_conversation_id')
                    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index('conversation_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('conversation_created_by_idx', ['created_by'], unique=False)

    op.create_table('dataset',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_dataset_id')
                    )
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index('dataset_account_id_name_idx', ['account_id', 'name'], unique=False)

    op.create_table('dataset_query',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('query', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('source', sa.String(length=255),
                              server_default=sa.text("'HitTesting'::character varying"), nullable=False),
                    sa.Column('source_app_id', sa.UUID(), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_dataset_query_id')
                    )
    with op.batch_alter_table('dataset_query', schema=None) as batch_op:
        batch_op.create_index('dataset_query_created_by_idx', ['created_by'], unique=False)
        batch_op.create_index('dataset_query_dataset_id_idx', ['dataset_id'], unique=False)
        batch_op.create_index('dataset_query_source_app_id_idx', ['source_app_id'], unique=False)

    op.create_table('document',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('upload_file_id', sa.UUID(), nullable=False),
                    sa.Column('process_rule_id', sa.UUID(), nullable=False),
                    sa.Column('batch', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('position', sa.Integer(), server_default=sa.text('1'), nullable=False),
                    sa.Column('character_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
                    sa.Column('parsing_completed_at', sa.DateTime(), nullable=True),
                    sa.Column('splitting_completed_at', sa.DateTime(), nullable=True),
                    sa.Column('indexing_completed_at', sa.DateTime(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('stopped_at', sa.DateTime(), nullable=True),
                    sa.Column('error', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_document_id')
                    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('document_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('document_batch_idx', ['batch'], unique=False)
        batch_op.create_index('document_dataset_id_idx', ['dataset_id'], unique=False)

    op.create_table('end_user',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('tenant_id', sa.UUID(), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_end_user_id')
                    )
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.create_index('end_user_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('end_user_tenant_id_idx', ['tenant_id'], unique=False)

    op.create_table('keyword_table',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('keyword_table', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_keyword_table_id')
                    )
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.create_index('keyword_table_dataset_id_idx', ['dataset_id'], unique=False)

    op.create_table('message',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('invoke_from', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=False),
                    sa.Column('query', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('message_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('message_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('message_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('answer', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('answer_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('error', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('total_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_message_id')
                    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('message_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_created_by_idx', ['created_by'], unique=False)

    op.create_table('message_agent_thought',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('message_id', sa.UUID(), nullable=False),
                    sa.Column('invoke_from', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=False),
                    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('event', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('tool', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('thought', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('observation', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                              nullable=False),
                    sa.Column('message_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('message_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('message_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'),
                              nullable=False),
                    sa.Column('answer', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('answer_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('total_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_message_agent_thought_id')
                    )
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.create_index('message_agent_thought_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('message_agent_thought_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_agent_thought_message_id_idx', ['message_id'], unique=False)

    op.create_table('process_rule',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('mode', sa.String(length=255), server_default=sa.text("'automic'::character varying"),
                              nullable=False),
                    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_process_rule_id')
                    )
    with op.batch_alter_table('process_rule', schema=None) as batch_op:
        batch_op.create_index('process_rule_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('process_rule_dataset_id_idx', ['dataset_id'], unique=False)

    op.create_table('segment',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('document_id', sa.UUID(), nullable=False),
                    sa.Column('node_id', sa.UUID(), nullable=False),
                    sa.Column('position', sa.Integer(), server_default=sa.text('1'), nullable=False),
                    sa.Column('content', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('character_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'[]'::jsonb"), nullable=False),
                    sa.Column('hash', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('hit_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('disabled_at', sa.DateTime(), nullable=True),
                    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
                    sa.Column('indexing_completed_at', sa.DateTime(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('stopped_at', sa.DateTime(), nullable=True),
                    sa.Column('error', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("'waiting'::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_segment_id')
                    )
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.create_index('segment_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('segment_dataset_id_idx', ['dataset_id'], unique=False)
        batch_op.create_index('segment_document_id_idx', ['document_id'], unique=False)

    op.create_table('upload_file',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('key', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('extension', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('mime_type', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('hash', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_upload_file_id')
                    )
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.create_index('upload_file_account_id_idx', ['account_id'], unique=False)

    op.create_table('workflow',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('tool_call_name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('draft_graph', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('is_debug_passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_workflow_id')
                    )
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index('workflow_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('workflow_tool_call_name_idx', ['tool_call_name'], unique=False)

    op.create_table('workflow_result',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=True),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('workflow_id', sa.UUID(), nullable=False),
                    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_workflow_result_id')
                    )
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.create_index('workflow_result_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('workflow_result_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow_result_workflow_id_idx', ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.drop_index('workflow_result_workflow_id_idx')
        batch_op.drop_index('workflow_result_app_id_idx')
        batch_op.drop_index('workflow_result_account_id_idx')

    op.drop_table('workflow_result')
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('workflow_tool_call_name_idx')
        batch_op.drop_index('workflow_account_id_idx')

    op.drop_table('workflow')
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_index('upload_file_account_id_idx')

    op.drop_table('upload_file')
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_index('segment_document_id_idx')
        batch_op.drop_index('segment_dataset_id_idx')
        batch_op.drop_index('segment_account_id_idx')

    op.drop_table('segment')
    with op.batch_alter_table('process_rule', schema=None) as batch_op:
        batch_op.drop_index('process_rule_dataset_id_idx')
        batch_op.drop_index('process_rule_account_id_idx')

    op.drop_table('process_rule')
    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_index('message_agent_thought_message_id_idx')
        batch_op.drop_index('message_agent_thought_conversation_id_idx')
        batch_op.drop_index('message_agent_thought_app_id_idx')

    op.drop_table('message_agent_thought')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('message_created_by_idx')
        batch_op.drop_index('message_conversation_id_idx')

    op.drop_table('message')
    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.drop_index('keyword_table_dataset_id_idx')

    op.drop_table('keyword_table')
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.drop_index('end_user_tenant_id_idx')
        batch_op.drop_index('end_user_app_id_idx')

    op.drop_table('end_user')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('document_dataset_id_idx')
        batch_op.drop_index('document_batch_idx')
        batch_op.drop_index('document_account_id_idx')

    op.drop_table('document')
    with op.batch_alter_table('dataset_query', schema=None) as batch_op:
        batch_op.drop_index('dataset_query_source_app_id_idx')
        batch_op.drop_index('dataset_query_dataset_id_idx')
        batch_op.drop_index('dataset_query_created_by_idx')

    op.drop_table('dataset_query')
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index('dataset_account_id_name_idx')

    op.drop_table('dataset')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('conversation_created_by_idx')
        batch_op.drop_index('conversation_app_id_idx')

    op.drop_table('conversation')
    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.drop_index('app_dataset_join_app_id_dataset_id_idx')

    op.drop_table('app_dataset_join')
    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.drop_index('app_config_version_app_id_idx')

    op.drop_table('app_config_version')
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index('app_config_app_id_idx')

    op.drop_table('app_config')
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('app_token_idx')
        batch_op.drop_index('app_account_id_idx')

    op.drop_table('app')
    with op.batch_alter_table('api_tool_provider', schema=None) as batch_op:
        batch_op.drop_index('api_tool_provider_name_idx')
        batch_op.drop_index('api_tool_provider_account_id_idx')

    op.drop_table('api_tool_provider')
    with op.batch_alter_table('api_tool', schema=None) as batch_op:
        batch_op.drop_index('api_tool_provider_id_name_idx')
        batch_op.drop_index('api_tool_account_id_idx')

    op.drop_table('api_tool')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index('api_key_api_key_idx')
        batch_op.drop_index('api_key_account_id_idx')

    op.drop_table('api_key')
    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.drop_index('account_oauth_openid_provider_idx')
        batch_op.drop_index('account_oauth_account_id_idx')

    op.drop_table('account_oauth')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('account_email_idx')

    op.drop_table('account')
    # ### end Alembic commands ###
