"""empty message

Revision ID: ba1f4b2aca6d
Revises: 01a8c3b2c207
Create Date: 2026-01-06 15:45:14.447135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba1f4b2aca6d'
down_revision = '01a8c3b2c207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('summary', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('invoke_from', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_conversation_id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('invoke_from', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('message_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'), nullable=False),
    sa.Column('message_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.0'), nullable=False),
    sa.Column('answer', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('answer_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'), nullable=False),
    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.0'), nullable=False),
    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('error', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('total_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_message_id')
    )
    op.create_table('message_agent_thought',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('invoke_from', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('event', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('message_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('message_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'), nullable=False),
    sa.Column('message_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('answer', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('answer_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('answer_unit_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'), nullable=False),
    sa.Column('answer_price_unit', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.0'), nullable=False),
    sa.Column('total_token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=7), server_default=sa.text('0.0'), nullable=False),
    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_message_agent_thought_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_agent_thought')
    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
