"""empty message

Revision ID: d6bdf91176b1
Revises: 05cc496ce3ce
Create Date: 2026-01-17 20:21:37.578613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6bdf91176b1'
down_revision = '05cc496ce3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggest_after_answer', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"enable": true}\'::jsonb'), nullable=False))

    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggest_after_answer', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"enable": true}\'::jsonb'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.drop_column('suggest_after_answer')

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('suggest_after_answer')

    # ### end Alembic commands ###
