"""empty message

Revision ID: d71652263ad4
Revises: d6bdf91176b1
Create Date: 2026-01-17 20:38:53.440241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd71652263ad4'
down_revision = 'd6bdf91176b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_after_answer', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"enable": true}\'::jsonb'), nullable=False))
        batch_op.drop_column('suggest_after_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggest_after_answer', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"enable": true}\'::jsonb'), autoincrement=False, nullable=False))
        batch_op.drop_column('suggested_after_answer')

    # ### end Alembic commands ###
