"""empty message

Revision ID: e16e1743cc37
Revises: f1be50c2de44
Create Date: 2025-12-30 19:37:18.912317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16e1743cc37'
down_revision = 'f1be50c2de44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
        batch_op.drop_column('mim_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mim_type', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
