"""empty message

Revision ID: f8d5ceebfa48
Revises: 9ec9bb42d145
Create Date: 2026-02-02 14:15:54.630755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d5ceebfa48'
down_revision = '9ec9bb42d145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_agent_conversation_id', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('assistant_agent_conversation_id')

    # ### end Alembic commands ###
