server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 核心配置：如果找不到资源，则统一返回 index.html
        try_files $uri $uri/ /index.html;
    }

    # 后续如果部署了后端，可以在这里配置反向代理
    # location /api {
    #    proxy_pass http://your_backend_ip:port;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}