version: '3.8'

services:
  # 前端服务配置
  frontend:
    container_name: zensnack-llmops-app
    build:
      # context 是相对于 docker-compose.yaml 文件的路径
      # 因为我们在 docker 目录下，所以需要跳到上级目录再进入 llmops-ui
      context: ../llmops-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    # 也可以给镜像起个固定的名字，方便识别
    image: zensnack-llmops-ui:latest
