version: '3.8'

services:
  # 前端服务配置
  frontend:
    container_name: zensnack-llmops-app
    build:
      # context 是相对于 docker-compose.yaml 文件的路径
      # 因为我们在 docker 目录下，所以需要跳到上级目录再进入 llmops-ui
      context: ../llmops-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    # 也可以给镜像起个固定的名字，方便识别
    image: zensnack-llmops-ui:latest
  
  # Redis 服务
  redis:
    image: redis:7-alpine # 使用轻量级的 alpine 版本
    container_name: zensnack-redis
    restart: always
    ports:
      - "6379:6379" # 将 Redis 默认端口映射出来
    volumes:
      - ./volumes/redis_data:/data # 数据持久化，防止容器重启后数据丢失
    command: redis-server --requirepass yourpassword123 # 设置 Redis 密码
  
  # postgres 服务
  db:
    image: postgres:16-alpine  # 使用 16 版本的轻量镜像
    container_name: zensnack-db
    restart: always
    environment:
      # 配置默认的账户名、账户密码、默认数据库、数据存储位置
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: llmops
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # 将postgres数据挂载到本地 ./volumes/db/data 上
      - ./volumes/postgres_data:/var/lib/postgresql/data/pgdata
      # 初始化脚本只有在空数据挂载的情况下才会触发执行（.sql/.sh等），如果已经存在数据则不会执行
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # 每隔1s发起一个健康测试，最多重试30次
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"

  # weaviate 服务
  llmops-weaviate:
    image: semitechnologies/weaviate:1.28.4
    container_name: zensnack-weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25  # 查询默认返回的数据条数
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'  # 需要授权才能和weaviate进行交互
      PERSISTENCE_DATA_PATH: /var/lib/weaviate  # weaviate数据存储路径
      DEFAULT_VECTORIZER_MODULE: 'none'  # 向量化模块设置为none
      CLUSTER_HOSTNAME: 'node1'  # 节点的主机名字
      AUTHENTICATION_APIKEY_ENABLED: 'true'  # 启动基于API秘钥的身份校验
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'ftBC8hKkjfdsci0wW1T6kEtMh5BZFpGa1AD8'  # 允许的API秘钥列表
      AUTHENTICATION_APIKEY_USERS: 'yin_991@163.com'  # 基于秘钥的API身份列表
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'  # 启动AdminList授权方案
      AUTHORIZATION_ADMINLIST_USERS: 'yin_991@163.com'  # 使用AdminList方案时具有管理权限的用户
    volumes:
      - ./volumes/weaviate_data:/var/lib/weaviate
    ports:
      - "8080:8080"
      - "50051:50051"

# 定义持久化卷
volumes:
  redis_data:
  postgres_data:
  weaviate_data: